version: "3.2"

services:
  owid-grapher:
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
    # https://stackoverflow.com/a/32785014/232619
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mysql:3306 --strict -- yarn dev
    env_file: 
      - .env
    ports:
      - 3030:3030
      - 8090:8090
    depends_on:
      - mysql
  
  mysql:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    restart: on-failure
    env_file:
      - docker/mysql/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./data_db:/var/lib/mysql
      - ./data_dump:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080